### ISSUE TITLE
Spelling Issue in randomspy.py

### ISSUE THREAD

**Issue by ep1nephrine** [presleyduggan/rand_spy#1]
On line 2: `warnings.filterwarnings('ignore') # ignore pandas depcreciated function warning`

The word "depcreciated" is actually not a word. I think you meant to use "deprecated"

This is making the program unusable for me and I would like you to fix it. Thanks!

**Comment by presleyduggan** [comment]
I think you mean depreciated

Thank you for showing me the error though.

**Comment by ep1nephrine** [comment]
I respectfully disagree Mr. Coder but I will respect your decision to be wrong.

**Comment by presleyduggan** [comment]
oops
